# Generated by Django 2.0.6 on 2018-08-05 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zaer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=1000)),
                ('mobile', models.CharField(blank=True, max_length=16)),
                ('birth_date', models.DateTimeField(blank=True, db_index=True)),
                ('in_date', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now)),
                ('out_date', models.DateTimeField(blank=True, db_index=True)),
                ('gender', models.CharField(blank=True, default='m', max_length=1)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
