# Generated by Django 2.0.6 on 2018-08-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaer', '0003_typo'),
    ]

    operations = [
        migrations.AddField(
            model_name='zaer',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
