# Generated by Django 2.0.6 on 2018-08-06 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zaer', '0004_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zaer',
            name='birth_date',
        ),
    ]
